// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDguBvu_BWlitBMplV8ddYnsii1epFqDBk',
    appId: '1:409723400130:web:fc85d2f51e7059140a305b',
    messagingSenderId: '409723400130',
    projectId: 'mynotes-65ee3',
    authDomain: 'mynotes-65ee3.firebaseapp.com',
    storageBucket: 'mynotes-65ee3.appspot.com',
    measurementId: 'G-16SX3RV51G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNBZ_Kk5GotmRgPxGeOoIUE7xcZTyGtqM',
    appId: '1:409723400130:android:dcc509c5aab17c6b0a305b',
    messagingSenderId: '409723400130',
    projectId: 'mynotes-65ee3',
    storageBucket: 'mynotes-65ee3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkXXJ8YGWl0WTqDwKA_aGnpP9f69YQ7ZI',
    appId: '1:409723400130:ios:870ce396ebf854050a305b',
    messagingSenderId: '409723400130',
    projectId: 'mynotes-65ee3',
    storageBucket: 'mynotes-65ee3.appspot.com',
    iosClientId: '409723400130-7iv9dou8ktlnidmd8mrplhi4bujhb5fa.apps.googleusercontent.com',
    iosBundleId: 'com.rinay.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkXXJ8YGWl0WTqDwKA_aGnpP9f69YQ7ZI',
    appId: '1:409723400130:ios:20d285d5740982630a305b',
    messagingSenderId: '409723400130',
    projectId: 'mynotes-65ee3',
    storageBucket: 'mynotes-65ee3.appspot.com',
    iosClientId: '409723400130-l691bcc479nnoq1j09dp38iblhrgqjpg.apps.googleusercontent.com',
    iosBundleId: 'com.rinay.mynotes.RunnerTests',
  );
}
